name: movesense_flutter
description: A flutter plugin project to interface with the Suunto Movesense device
version: 0.0.5
homepage: https://gitlab.com/bluesquall/movesense_flutter

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: works.otter.movesense_flutter
        pluginClass: MovesenseFlutterPlugin

